# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6bedf0cce8aae090c9248740c331d68fef603016ca036114cfdad50d5d4fb646a58b753c4f94b8baf9c1e8703b3cfe1642acb58fe67864079227692a390e24

test:
  secret_key_base: 85221812d97a1ca4c24711af6429cf8ca3d07a48c6482c1f051e2e4609eef4e1b8bff1dfab7a0e7311920b6892048d100d779567d7c639b0513bd883038505a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
